name: Deploy to Alibaba ECS

on:
  push:
    branches:
      - main  # Menjalankan deployment ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to ECS
        run: |
          ssh -o StrictHostKeyChecking=no root@8.219.173.224 << EOF
          cd /var/www/mywebsite/runningCICD
          git pull origin main
          # Restart Nginx atau layanan lain jika diperlukan
          sudo systemctl restart nginx
          EOF
